enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music-Extended]
enabled = true
app-name = "Music"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "ReVanced Extended"
included-patches = "'Background play' 'Bitrate default value' 'Certificate spoof' 'Custom playback speed' 'Enable force minimized player' 'Enable minimized playback' 'Enable opus codec' 'Exclusive audio playback' 'Hide general ads' 'Hide get premium' 'Return YouTube Dislike' 'Sanitize sharing links' 'Settings'"
exclusive-patches = true
build-mode = "module"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"

[YouTube-Extended]
enabled = true
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "ReVanced Extended"
included-patches = "'Hide video ads' 'Hide general ads' 'Remove viewer discretion dialog' 'Enable minimized playback' 'Sanitize sharing links' 'Enable open links directly' 'Enable external browser' 'Custom playback speed' 'Default video quality' 'Return YouTube Dislike' 'Force opus codec' 'Force video codec' 'Force fullscreen' 'Settings' 'Spoof player parameters'"
exclusive-patches = true
build-mode = "module"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
version = "19.16.38"
